name: Build and test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0-rc.1' # The Go version to download (if necessary) and use.
      - name: Setup golang
        run: make tomo
    
