name: Build and test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0-rc.1' # The Go version to download (if necessary) and use.
      - name: Use golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.53
          timeout: 30m
      - name: Install golangci-lint
        run:
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.18.0
        env:
          GOPATH: /home/runner/work/woodpecker/go
      - name: Lint code
        run: golangci-lint run --disable-all --enable=vet --enable=gofmt --enable=misspell --enable=goconst --min-occurrences=6
        env:
          GOPATH: /home/runner/work/woodpecker/go
      - name: Build tomo
        run: go run build/ci.go install
      - name: Test tomo
        run: go run build/ci.go test -coverage
    
