name: Build and test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0-rc.1' # The Go version to download (if necessary) and use.
      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
      - name: Build tomo
        run: go run build/ci.go install
      - name: Test tomo
        run: go run build/ci.go test -coverage
    
